name: "bookshelf-backend"

services:
  app:
    build: .
    ports:
      - 8080:8080
    env_file: .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - net

  db:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 60s 
    networks:
      - net

networks:
  net:
